name: Tests

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  verify_generated_files:
    name: Verify Generated Files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install dotnet-format
        run: dotnet tool install --global --version 5.0.211103 dotnet-format
      - name: Download Drivers
        run: dotnet run -p ./src/tools/Playwright.Tooling/Playwright.Tooling.csproj -- download-drivers --basepath .
      - name: Read commit SHA
        id: read-upstream-commit-sha
        run: echo "::set-output name=hash::$(cat src/Playwright/.drivers/linux/package/commitinfo)"
      - uses: actions/checkout@v2
        with:
          repository: 'microsoft/playwright'
          ref: ${{ steps.read-upstream-commit-sha.outputs.hash }}
          path: 'playwright'
      - name: Generate
        run: |
          node playwright/utils/doclint/generateDotnetApi.js src/Playwright
          rm -rf playwright
      - name: Verify generated API is up to date
        run: git diff --exit-code